---
title: "First Post"
date: "May 30, 2022"
---

### What?
Why, hello there.
My name is Edward (which you probably already knew one way or another). 

You might be wondering why the first section of the first post starts with “Why?” but let’s talk about that later.

So, the tl;dr is that I’ve decided to start a machine learning blog. Hopefully, this side-gig lasts longer than my last one…

I’m mostly going to be writing some articles about random topics I either encountered online or topics I didn’t know about and happened to stumble across when I had a random idea for a machine learning algorithm (I bet you most of them are useless, but it’s fun implementing them anyways and seeing how they perform).

I might also write about other things I’m learning about, and those topics will likely extend broadly to math, computer science, and maybe even stuff such as blockchain and cryptocurrency (still learning the baby steps on this one).

Most of the posts will probably follow the same structure as this post, i.e.:

 - What?
   + The section where I talk about what I’m going to talk about. 
 - Why?
   + The section where how the topic I’m going to talk about is interesting or worth knowing about (in my own words, so might not be perfect).
 - How?
   + The section where I talk about how the thing we’ve been talking about up until now actually works. 
 - Additional Notes
   + Any additional stuff I want to mention.
 - Resource List
   + A list of resources I looked through to make the post.
 - Final Notes
   + Just me saying bye.
With all that said, I’ll try to follow this structure in my first post and consider it as practice for writing a blog. 

### Why?
In recent times, I’ve realized that I’ve been bulldozering through a lot of interesting things where I read through resources in a frenzy but forget everything I read in a few months. I hope that this blog can help me concretize the things I learn and also serve as a reference for future me when I forget the specifics of what I learned.

### How?
The “How” for this post is pretty self-explanatory; I’ll just be be posting stuff here once in a while (I’m not sure about the frequency yet). 

I’m not sure how I’ll be organizing the “How?” for future sections as I’m sure the optimal structure will vary depending on the specific topic, so I’ll keep it flexible but hopefully they’ll still be logically easy to follow.

### Additional Notes
I’m not sure how I’ll manage to add these posts to my website as of writing this, so I’m not sure if there will be a comment feature. If there is one (and even if there isn’t one, although it will make you do a bit more work), please leave a comment if I made a mistake, or you can suggest additional resources on the topic, or any thoughts you have, or anything else. 

EDIT: Still struggling to add a comment section. 

EDIT 2: Never mind, but you apparently need a GitHub account...

### Resource List:
None, of course.

### Final Notes 
Bye! 

Hopefully I’ll see you soon (or rather, hopefully you’ll see me soon, because if you don’t then that means I’ve already stopped writing posts, which would be a bit pathetic).
